export const appImage = {
  logo: require('../../assets/image/logo.png'),
  home: require('../../assets/image/home.png'),
  back: require('../../assets/image/back.png'),
  closeEye: require('../../assets/image/closeEye.png'),
  email: require('../../assets/image/email.png'),
  facebook: require('../../assets/image/facebook.png'),
  google: require('../../assets/image/google.png'),
  lock: require('../../assets/image/lock.png'),
  settings: require('../../assets/image/settings.png'),
  macaron_logo: require('../../assets/image/macaron_logo.png'),
  phone: require('../../assets/image/phone.png'),
  twitter: require('../../assets/image/twitter.png'),
  user: require('../../assets/image/user.png'),
  drawer: require('../../assets/image/drawer.png'),
};
